[paths]
data = "./data.nc"

[coefficients]
diffusion = [1, 100]
breed = [1, 100]
spread = [1, 100]
slope = [1, 100]
road = [1, 100]

[misc]
critical_slope = 50

[refinement]
iterations = 3
splits = 5
winners = 3

[montecarlo]
iterations = 10
# random_seed = 42

[multiprocessing]
threads = -1

[calibration]
start_year = 2000